# Generated by Django 4.1.4 on 2022-12-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
