# Generated by Django 4.1.4 on 2022-12-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0002_venue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.TextField(max_length=200),
        ),
    ]
